# Generated by Django 4.1.3 on 2023-04-08 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_booking_booking_code_alter_diary_entry_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_code',
            field=models.CharField(default='D-930876U', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='diary',
            name='entry_code',
            field=models.CharField(default='Z-771928T', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.snippetcategory'),
        ),
        migrations.AlterField(
            model_name='snippetcategory',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
