# Generated by Django 4.1.3 on 2023-04-08 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_booking_booking_code_alter_diary_entry_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_code',
            field=models.CharField(default='I-474495P', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='diary',
            name='entry_code',
            field=models.CharField(default='W-936825G', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='snippetcategory',
            name='title',
            field=models.CharField(default='all', max_length=100, unique=True),
        ),
    ]
