# Generated by Django 4.1.3 on 2023-04-12 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_booking_booking_code_alter_diary_entry_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='KnowledgeThematic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_code',
            field=models.CharField(default='U-403452V', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='diary',
            name='entry_code',
            field=models.CharField(default='O-195179Y', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='Knowledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('info', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('knowledge_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.knowledgesection')),
                ('knowledge_thematic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.knowledgethematic')),
            ],
        ),
    ]
