# Generated by Django 4.1.3 on 2023-04-12 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_knowledge_status_alter_booking_booking_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledge',
            name='visited',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_code',
            field=models.CharField(default='U-580762O', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='diary',
            name='entry_code',
            field=models.CharField(default='L-895881F', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
