# Generated by Django 4.1.3 on 2023-04-12 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_booking_booking_code_alter_diary_entry_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgethematic',
            name='knowledge_section',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.knowledgesection'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_code',
            field=models.CharField(default='B-217193Q', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='diary',
            name='entry_code',
            field=models.CharField(default='I-388110M', max_length=255, unique=True),
        ),
    ]
