# Generated by Django 4.1.3 on 2023-05-24 11:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_cashier_closure_customer_departmentmaingroup_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_code',
            field=models.CharField(default='R-577964D', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='closure',
            name='closure_unique_id',
            field=models.UUIDField(verbose_name=uuid.UUID('0c0d78f2-785d-4af9-82c5-f293cf838397')),
        ),
        migrations.AlterField(
            model_name='diary',
            name='entry_code',
            field=models.CharField(default='K-260883X', max_length=255, unique=True),
        ),
    ]
