# Generated by Django 4.1.3 on 2023-05-24 12:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_alter_booking_booking_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_code',
            field=models.CharField(default='H-260890H', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='closure',
            name='closure_unique_id',
            field=models.UUIDField(verbose_name=uuid.UUID('2c3ff8db-59eb-42a9-8f66-b4080fe9423a')),
        ),
        migrations.AlterField(
            model_name='diary',
            name='entry_code',
            field=models.CharField(default='I-110413R', max_length=255, unique=True),
        ),
        migrations.CreateModel(
            name='ProductBarcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(max_length=50)),
                ('is_allowed_negative_stock', models.BooleanField()),
                ('is_allowed_return', models.BooleanField()),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField()),
                ('description', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fk_cashier_create_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='product_barcode_cashier_created', to='accounts.cashier')),
                ('fk_cashier_update_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='product_barcode_cashier_updated', to='accounts.cashier')),
                ('fk_product_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='product_barcode_product', to='accounts.product')),
            ],
        ),
    ]
