# Generated by Django 4.1.3 on 2023-05-24 12:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_alter_booking_booking_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_code',
            field=models.CharField(default='G-658139C', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='closure',
            name='closure_unique_id',
            field=models.UUIDField(verbose_name=uuid.UUID('f9e3a923-a33a-4df3-b30a-66875833da8f')),
        ),
        migrations.AlterField(
            model_name='diary',
            name='entry_code',
            field=models.CharField(default='M-203441J', max_length=255, unique=True),
        ),
        migrations.CreateModel(
            name='ProductUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('no', models.IntegerField()),
                ('description', models.TextField(null=True)),
                ('base_id', models.IntegerField()),
                ('base_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('symbol', models.CharField(max_length=10)),
                ('is_deleted', models.BooleanField(default=False)),
                ('delete_description', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fk_cashier_create_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='product_unit_cashier_created', to='accounts.cashier')),
                ('fk_cashier_update_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='product_unit_cashier_updated', to='accounts.cashier')),
            ],
        ),
    ]
