# Generated by Django 4.1.3 on 2023-05-24 13:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_transactiondiscount_transactionhead_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactiondiscount',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transactiondiscount',
            name='delete_description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='transactiondiscount',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transactiondiscount',
            name='discount_code',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='transactiondiscount',
            name='discount_rate',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='transactiondiscount',
            name='discount_type',
            field=models.CharField(default='res', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transactiondiscount',
            name='fk_cashier_create_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='transaction_dicount_cashier_created', to='accounts.cashier'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transactiondiscount',
            name='fk_cashier_update_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='transaction_dicount_cashier_updated', to='accounts.cashier'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transactiondiscount',
            name='fk_transaction_head_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='transaction_dicount_head', to='accounts.transactionheadtemp'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transactiondiscount',
            name='fk_transaction_payment_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='transaction_dicount_payment', to='accounts.transactionpaymenttemp'),
        ),
        migrations.AddField(
            model_name='transactiondiscount',
            name='fk_transaction_product_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='transaction_dicount_product', to='accounts.transactionproducttemp'),
        ),
        migrations.AddField(
            model_name='transactiondiscount',
            name='fk_transaction_total_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='transaction_dicount_total', to='accounts.transactiontotaltemp'),
        ),
        migrations.AddField(
            model_name='transactiondiscount',
            name='is_cancel',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transactiondiscount',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transactiondiscount',
            name='line_no',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transactiondiscount',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_code',
            field=models.CharField(default='M-60583A', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='closure',
            name='closure_unique_id',
            field=models.UUIDField(verbose_name=uuid.UUID('9edd3cc4-6a12-4aba-bfc5-33b8073ceeb9')),
        ),
        migrations.AlterField(
            model_name='diary',
            name='entry_code',
            field=models.CharField(default='P-100471C', max_length=255, unique=True),
        ),
    ]
