# Generated by Django 4.1.3 on 2023-05-24 13:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_transactiondiscount_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionhead',
            name='closure_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transactionhead',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transactionhead',
            name='delete_description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='transactionhead',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transactionhead',
            name='document_type',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transactionhead',
            name='fk_cashier_create_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='transaction_head_cashier_created', to='accounts.cashier'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transactionhead',
            name='fk_cashier_update_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='transaction_head_cashier_updated', to='accounts.cashier'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transactionhead',
            name='fk_customer_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='transaction_head_customer_id', to='accounts.customer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transactionhead',
            name='is_cancel',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transactionhead',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transactionhead',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transactionhead',
            name='is_pending',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transactionhead',
            name='pos_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transactionhead',
            name='receipt_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transactionhead',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transactionhead',
            name='total_change_amount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transactionhead',
            name='total_discount_amount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transactionhead',
            name='total_payment_amount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transactionhead',
            name='total_surcharge_amount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transactionhead',
            name='total_vat_amount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transactionhead',
            name='transaction_date_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transactionhead',
            name='transaction_unique_id',
            field=models.URLField(default=1, verbose_name=uuid.UUID('ba776950-e4e5-4dc0-a8a1-b1b2a445b172')),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transactionhead',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='transactionheadtemp',
            name='batch_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transactionheadtemp',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transactionheadtemp',
            name='delete_description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='transactionheadtemp',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transactionheadtemp',
            name='document_type',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transactionheadtemp',
            name='fk_cashier_create_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='transaction_head_temp_cashier_created', to='accounts.cashier'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transactionheadtemp',
            name='fk_cashier_update_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='transaction_head_temp_cashier_updated', to='accounts.cashier'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transactionheadtemp',
            name='fk_customer_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='transaction_head_temp_customer_id', to='accounts.customer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transactionheadtemp',
            name='is_cancel',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transactionheadtemp',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transactionheadtemp',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transactionheadtemp',
            name='is_pending',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transactionheadtemp',
            name='pos_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transactionheadtemp',
            name='receipt_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transactionheadtemp',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transactionheadtemp',
            name='total_change_amount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transactionheadtemp',
            name='total_discount_amount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transactionheadtemp',
            name='total_payment_amount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transactionheadtemp',
            name='total_surcharge_amount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transactionheadtemp',
            name='total_vat_amount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transactionheadtemp',
            name='transaction_date_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transactionheadtemp',
            name='transaction_unique_id',
            field=models.URLField(default=1, verbose_name=uuid.UUID('df3f7e5a-23ab-402a-b4d7-1f017ab63b91')),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transactionheadtemp',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='transactionpaymenttemp',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transactionpaymenttemp',
            name='currency_code',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transactionpaymenttemp',
            name='currency_exchange_rate',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transactionpaymenttemp',
            name='currency_total',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transactionpaymenttemp',
            name='delete_description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='transactionpaymenttemp',
            name='fk_cashier_create_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='transaction_head_temp1_cashier_created_id', to='accounts.cashier'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transactionpaymenttemp',
            name='fk_cashier_update_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='transaction_head_temp1_cashier_updated_id', to='accounts.cashier'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transactionpaymenttemp',
            name='installment_count',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transactionpaymenttemp',
            name='is_cancel',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transactionpaymenttemp',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transactionpaymenttemp',
            name='line_no',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transactionpaymenttemp',
            name='payment_tool_id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='transactionpaymenttemp',
            name='payment_total',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transactionpaymenttemp',
            name='payment_type',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transactionpaymenttemp',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_code',
            field=models.CharField(default='X-844095D', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='closure',
            name='closure_unique_id',
            field=models.UUIDField(verbose_name=uuid.UUID('0ef82f75-55ad-4e8e-95cd-4138d2be4959')),
        ),
        migrations.AlterField(
            model_name='diary',
            name='entry_code',
            field=models.CharField(default='R-167950G', max_length=255, unique=True),
        ),
    ]
