# Generated by Django 4.1.3 on 2023-05-24 13:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_transactionhead_closure_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionpaymenttemp',
            name='fk_transaction_head_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='transaction_head_temp1_id', to='accounts.transactionheadtemp'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_code',
            field=models.CharField(default='Z-707131G', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='closure',
            name='closure_unique_id',
            field=models.UUIDField(verbose_name=uuid.UUID('3fadf8d6-7b11-493c-84cf-bc4e79ab5a4c')),
        ),
        migrations.AlterField(
            model_name='diary',
            name='entry_code',
            field=models.CharField(default='Z-269135L', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='transactionhead',
            name='transaction_unique_id',
            field=models.URLField(verbose_name=uuid.UUID('717a8656-9e4e-4627-8098-4ec14ce10e28')),
        ),
        migrations.AlterField(
            model_name='transactionheadtemp',
            name='transaction_unique_id',
            field=models.URLField(verbose_name=uuid.UUID('5ffc5ff6-4719-40d3-bd8e-1e721eef92dc')),
        ),
    ]
