# Generated by Django 4.1.3 on 2023-05-24 14:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_transactionpayment_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionproducttemp',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transactionproducttemp',
            name='delete_description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='transactionproducttemp',
            name='fk_cashier_create_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='transaction_product_temp_cashier_created', to='accounts.cashier'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transactionproducttemp',
            name='fk_cashier_update_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='transaction_product_temp_cashier_updated', to='accounts.cashier'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transactionproducttemp',
            name='fk_department_main_group_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='department_main_grp', to='accounts.departmentmaingroup'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transactionproducttemp',
            name='fk_department_sub_group_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='department_subgrp_id', to='accounts.departmentsubgroup'),
        ),
        migrations.AddField(
            model_name='transactionproducttemp',
            name='fk_product_barcode_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='broduct_barcode_1', to='accounts.productbarcode'),
        ),
        migrations.AddField(
            model_name='transactionproducttemp',
            name='fk_product_barcode_mask_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='product_barcode_mask_1', to='accounts.productbarcodemask'),
        ),
        migrations.AddField(
            model_name='transactionproducttemp',
            name='fk_product_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='transaction_product_id', to='accounts.product'),
        ),
        migrations.AddField(
            model_name='transactionproducttemp',
            name='fk_transaction_head_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='transaction_head_temp_ident', to='accounts.transactionheadtemp'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transactionproducttemp',
            name='is_cancel',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transactionproducttemp',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transactionproducttemp',
            name='line_no',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transactionproducttemp',
            name='total_discount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transactionproducttemp',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transactionproducttemp',
            name='total_vat',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transactionproducttemp',
            name='unit_discount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transactionproducttemp',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transactionproducttemp',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='transactionproducttemp',
            name='vat_rate',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_code',
            field=models.CharField(default='H-542955R', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='closure',
            name='closure_unique_id',
            field=models.UUIDField(verbose_name=uuid.UUID('259109ee-71d2-4af8-9640-c6d3008ed609')),
        ),
        migrations.AlterField(
            model_name='diary',
            name='entry_code',
            field=models.CharField(default='Q-319110I', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='transactionhead',
            name='transaction_unique_id',
            field=models.URLField(verbose_name=uuid.UUID('63fce7b1-e2ee-4cf6-b524-f740d8f4b9a0')),
        ),
        migrations.AlterField(
            model_name='transactionheadtemp',
            name='transaction_unique_id',
            field=models.URLField(verbose_name=uuid.UUID('7a1b3e3f-78dd-4a2d-af6b-55060cafbd80')),
        ),
    ]
