# Generated by Django 4.1.3 on 2023-05-24 14:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_transactionproduct_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactiontotaltemp',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transactiontotaltemp',
            name='delete_description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='transactiontotaltemp',
            name='fk_cashier_create_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='transaction_total_temp_cashier_created_id', to='accounts.cashier'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transactiontotaltemp',
            name='fk_cashier_update_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='transaction_total_temp_cashier_updated_id', to='accounts.cashier'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transactiontotaltemp',
            name='fk_department_main_group_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='total_department_main_grp', to='accounts.departmentmaingroup'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transactiontotaltemp',
            name='fk_transaction_head_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='total_transaction_head_temp1_id', to='accounts.transactionheadtemp'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transactiontotaltemp',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transactiontotaltemp',
            name='line_no',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transactiontotaltemp',
            name='total_department',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transactiontotaltemp',
            name='total_department_vat',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transactiontotaltemp',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_code',
            field=models.CharField(default='R-806653O', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='closure',
            name='closure_unique_id',
            field=models.UUIDField(verbose_name=uuid.UUID('269c7430-8643-4a0c-bee2-21c40cdec851')),
        ),
        migrations.AlterField(
            model_name='diary',
            name='entry_code',
            field=models.CharField(default='Z-424977L', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='transactionhead',
            name='transaction_unique_id',
            field=models.URLField(verbose_name=uuid.UUID('7ec6afb2-7984-4825-98fd-cefc6a746aed')),
        ),
        migrations.AlterField(
            model_name='transactionheadtemp',
            name='transaction_unique_id',
            field=models.URLField(verbose_name=uuid.UUID('7137a28b-c8ff-435c-ab49-b4682756cf3d')),
        ),
    ]
